control/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='controlIndex'),

    path('api/places', views.places, name='apiPlaces'),
    path('api/delete', views.delete_place, name='apiDelete'),
    path('api/uploadphoto', views.upload_image, name='apiUpload'),
    path('api/deletephoto', views.delete_image, name="apiDeletePhoto"),
    path('api/uploadplace', views.upload_place, name='apiUploadPlace'),
    path('api/editplace', views.edit_place, name="apiEditPlace"),
    path('api/code', views.get_code, name='apiCode'),
    path('api/checknotify', views.check_notification, name='apiCheckNotify'),
    path('api/ban', views.ban, name="apiBan"),
    path('api/edit', views.to_edit, name="apiEdit"),
    path('api/info', views.get_info, name="apiInfo"),
    path('api/org', views.get_org, name="apiInfoOrg"),
    path('api/editInstagram', views.edit_instagram, name="apiEditIns"),
    path('api/editOrg', views.edit_org, name="apiEditOrg"),

    path('report/', views.report_form, name='report'),
    path('photo', views.show_photo, name="showPhoto")
]

info/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('organizations', views.search, name='searchOrganization'),
    path('become', views.become, name='become'),
    path('about_us', views.about_us, name="aboutus"),
    path('terms_and_conditions', views.terms, name="terms"),
    path('organization/<int:pk>', views.organization, name='org'),
    path('categories/', views.choose_category, name='choose'),
    path('categories/<str:category>', views.category, name='category'),

    path('api/organizations', views.api_search, name='apiSearchOrg'),
    path('api/orgpoints', views.api_org, name='apiHelpOrg'),
    path('api/category', views.api_category, name='apiCategory')
]

small_actions/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('maps.urls')),
    path('account/', include('login.urls')),
    path('info/', include('info.urls')),
    path('control/', include('control.urls')),
    path("ads.txt", TemplateView.as_view(template_name="emails/ads.txt", content_type="text/plain")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

control/models.py
from django.db import models

from login.models import User
from maps.models import Help

# Create your models here.

class Report(models.Model):
    user_that_report = models.ForeignKey(User, on_delete=models.CASCADE)

    organization_or_user_options = [
        ('U', 'Usuario'),
        ('O', 'Organización')
    ]
    organization_or_user = models.CharField(max_length=1, choices=organization_or_user_options)
    name_of_reported = models.CharField(max_length=64)

    categories_options = [
        ('IfEn', 'Informacion Engañosa'),
        ('MaCa', 'Mal Categorizado'),
        ('CoSe', 'Contenido Sexual'),
        ('CoOf', 'Contenido Ofensivo'),
        ('CoPo', 'Contenido Politico'),
        ('AcIl', 'Actividades Ilegales'),
        ('Ment', 'Mentiras'),
        ('MaUb', 'Mala Ubicacion'),
        ('MaCo', 'No dan codigo'),
        ('Bane', 'Me bannearon sin motivo'),
        ('MaIn', 'Falta de informacion o informacion no clara'),
        ('Otro', 'Otro Motivo'),
    ]

    category_of_problem = models.CharField(max_length=4, choices=categories_options)
    decription_of_the_problem = models.TextField()

class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    help_point = models.ForeignKey(Help, on_delete=models.CASCADE)
    discarted = models.BooleanField(default=False) #To discard the notification
    points_earned = models.PositiveIntegerField()
    aproved = models.BooleanField(default=False) #Aproved or not the person, to later stadistics
    date = models.DateTimeField(auto_now_add=True)

control/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings
from django.http import JsonResponse, HttpResponse
from django.core.mail import send_mail
from django.conf import settings

from .froms import ReportForm, CreatePlace, CreatePhoto, EditInstagram, EditOrg
from .models import Report, Notification
from .decorators import allowed

from login.models import User
from maps.models import Help, HelpPhoto
from info.models import InstagramPublication, Organization

import json
import random
import string
# Create your views here.

@login_required(login_url='/account/login')
@allowed(allowed_roles=['Organization'])
def index(request):
    return render(request, 'control/index.html')

@login_required(login_url='/account/login')
@allowed(allowed_roles=['Organization'])
def show_photo(request):
    photo = HelpPhoto.objects.get(id=request.GET['id'])
    return HttpResponse(f'<img src="{photo.photo.url}">')

@login_required(login_url='/account/login')
@allowed(allowed_roles=['Organization'])
def get_org(request):
    if request.method != 'GET':
        return JsonResponse({'error' : 'Invalid request'}, status=400)

    user = User.objects.get(username=request.user.username)
    org = user.organization

    response = {
        'name' : org.name,
        'phone_number' : org.phone_number,
        'image' : org.image.url,
        'circular_icon' : org.circular_icon.url,
        'short_description' : org.short_description,
        'quote' : org.quote,
        'instagram_photos' : [{'url' : ins.url, 'id' : ins.id} for ins in org.instagram_photos.all()],
        'id' : org.id
    }

    return JsonResponse(response, status=200)

@login_required(login_url='/account/login')
@allowed(allowed_roles=['Organization'])
def edit_org(request):
    if request.method != 'POST':
        return JsonResponse({'error' : 'Invalid request'}, status=400)
    
    org = Organization.objects.get(pk=request.POST['id'])
    form = EditOrg(request.POST, request.FILES, instance=org)
    if form.is_valid():
        org.name = form.cleaned_data['name']
        org.phone_number = form.cleaned_data['phone_number']
        org.short_description = form.cleaned_data['short_description']
        org.quote = form.cleaned_data['quote']

        if form.cleaned_data['image'] != "undefined":
            org.image = form.cleaned_data['image'] 
        if form.cleaned_data['circular_icon'] != "undefined":
            org.circular_icon = form.cleaned_data['circular_icon'] 

        org.save()
        return JsonResponse({'mesagge' : 'All ok'}, status=200)

    return JsonResponse({'error' : 'Invalid form'}, status=400)

@login_required(login_url='/account/login')
@allowed(allowed_roles=['Organization'])
def edit_instagram(request):
    if request.method != 'POST':
        return JsonResponse({'error' : 'Invalid request'}, status=400)
    
    form = EditInstagram(request.POST)
    if form.is_valid():
        post = InstagramPublication.objects.get(pk=request.POST['id'])
        post.url = form.cleaned_data['url']
        post.save()
        return JsonResponse({'message' : f'{post.id} saved'}, status=200)

    return JsonResponse({'error' : 'Invalid form'}, status=400)

@login_required(login_url='/account/login')
@allowed(allowed_roles=['Organization'])
def to_edit(request):
    if request.method != 'POST':
        return JsonResponse({'error' : 'Invalid request'}, status=400)

    data = json.loads(request.body)
    if 'uuid' in data:
        place = Help.objects.get(uuid=data['uuid'])
        palce_info = {
            'organization' : place.organization.id,
            'latitude' : place.latitude,
            'longitude' : place.longitude,
            'mayor_category' : place.mayor_category,
            'category' : place.category.id,
            'sub_category' : place.sub_category.all()[0].id,
            #Util data
            'name' : place.name,
            'short_description' : place.short_description,
            'recomedations' : place.recomedations,
            'uuid' : place.uuid
        }

        photos_id = [photo.id for photo in place.photos.all()]
        return JsonResponse({'form' : palce_info, 'photosId' : photos_id}, status=200)

    
    return JsonResponse({'error' : 'No uuid especified'}, status=400)

@login_required(login_url='/account/login')
@allowed(allowed_roles=['Organization'])
def get_code(request):
    if request.method != 'POST':
        return JsonResponse({'error' : 'Invalid request'}, status=400)

    data = json.loads(request.body)
    if 'uuid' in data:
        place = Help.objects.get(uuid=data['uuid'])

        notifications = Notification.objects.filter(help_point=place, discarted=False)
        notification_list = []

        for notification in notifications:
            photo_url = notification.user.photo.url if notification.user.photo != '' else '/static/maps/images/logo_small_icon_only_inverted.png' #Check user have photo

            notification_list.append({
                'id' : notification.id,
                'username' : notification.user.username,
                'photo' : photo_url
            })

        return JsonResponse({'code' : place.temporal_code, 'notifications' : notification_list}, status=200)

    return JsonResponse({'error' : 'No uuid especified'}, status=400)

@login_required(login_url='/account/login')
@allowed(allowed_roles=['Organization'])
def check_notification(request):
    if request.method != 'POST':
        return JsonResponse({'error' : 'Invalid request'}, status=400)

    data = json.loads(request.body)
    if 'id' in data and 'aproved' in data:

        notify = Notification.objects.get(id=data['id'])
        if data['aproved'] == False:
            notify.user.points = notify.user.points - notify.points_earned #Rest the points earned
            notify.user.visited.remove(notify.help_point) #Delete visited place
            notify.user.save()

        notify.discarted = True
        notify.aproved = data['aproved']
        notify.save()

        return JsonResponse({'message' : 'ok'}, status=200)

    return JsonResponse({'error' : 'No id or aproved especified'}, status=400)

@login_required(login_url='/account/login')
@allowed(allowed_roles=['Organization'])
def ban(request):
    if request.method != 'POST':
        return JsonResponse({'error' : 'Invalid request'}, status=400)

    data = json.loads(request.body)
    if 'id' in data:
        notify = Notification.objects.get(id=data['id'])
        notify.user.points = notify.user.points - notify.points_earned #Rest the points earned in case the account is recuperated
        notify.user.visited.remove(notify.help_point) #Delete visited place
        notify.user.is_active = False #Ban User
        notify.user.save()

        send_mail('Tu cuenta fue baneada de Small Actions',
            f"""Tu cuenta {notify.user.username} fue baneada por {notify.help_point.organization.name}.
            Si crees que se trata de un error comunicate a https://api.whatsapp.com/send?phone=573023986488""",
            settings.EMAIL_HOST_USER,
            [notify.user.email]
        ) #Send email to notify the ban

        notify.discarted = True
        notify.aproved = False
        notify.save()

        return JsonResponse({'message' : f'{notify.user.username} has been banned'}, status=200)

    return JsonResponse({'error' : 'No id aproved especified'}, status=400)

@login_required(login_url='/account/login')
@allowed(allowed_roles=['Organization'])
def places(request):
    if request.method != 'GET':
        return JsonResponse({'error' : 'Invalid request'}, status=400)

    user = User.objects.get(username=request.user.username)
    organization = user.organization

    response = {'places' : []}
    for place in organization.help_points.all().order_by('-data_created'):
        response['places'].append({
            'name' : place.name,
            'image' : place.photos.all()[0].photo.url,
            'url' : reverse('info', kwargs={'uuid' : place.uuid}),
            'uuid' : place.uuid,
            'hover' : False
        })

    return JsonResponse(response, status=200)

@login_required(login_url='/account/login')
@allowed(allowed_roles=['Organization'])
def delete_place(request):
    if request.method != 'POST':
        return JsonResponse({'error' : 'Invalid request'}, status=400)
        
    data = json.loads(request.body)

    if 'uuid' in data and data['uuid'] != '':
        help_to_delete = Help.objects.get(uuid=data['uuid'])
        for photo in help_to_delete.photos.all():
            photo.delete()
        help_to_delete.delete()
        return JsonResponse({'message' : 'sucecess'}, status=200)

    return JsonResponse({'error' : 'No data specified'}, status=400)

@login_required(login_url='/account/login')
@allowed(allowed_roles=['Organization'])
def upload_image(request):
    if request.method != 'POST':
        return JsonResponse({'error' : 'Invalid request'}, status=400)
    
    form = CreatePhoto(request.POST, request.FILES)
    if form.is_valid():
        new_photo = HelpPhoto.objects.create(
            photo=form.cleaned_data['photo']
        )
        return JsonResponse({'id' : new_photo.id}, status=200)

    return JsonResponse({'error' : 'Invalid Photo Form'}, status=400)

@login_required(login_url='/account/login')
@allowed(allowed_roles=['Organization'])
def delete_image(request):
    if request.method != 'POST':
        return JsonResponse({'error' : 'Invalid request'}, status=400)
    
    data = json.loads(request.body)
    if 'id' in data and data['id'] != None:
        HelpPhoto.objects.get(id=data['id']).delete()
    
    return JsonResponse({'error' : 'No id or id null'}, status=400)

@login_required(login_url='/account/login')
@allowed(allowed_roles=['Organization'])
def get_info(request):
    if request.method != 'POST':

templates/control/index.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
    <head>
        <title>Panel de Control</title>
        <script src="{% static 'control/javascript/react.production.min.js' %}" ></script>
        <script src="{% static 'control/javascript/react-dom.production.min.js' %}" ></script>

        <script src="https://kit.fontawesome.com/7c5129238c.js" crossorigin="anonymous"></script>

        <link href="{% static 'control/css/fonts.css' %}" rel="stylesheet">

        <script src="{% static 'control/javascript/mapbox-gl.js' %}"></script>
        <link href="{% static 'control/css/mapbox-gl.css' %}" rel='stylesheet' />
        <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.5.1/mapbox-gl-geocoder.min.js"></script>
        <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.5.1/mapbox-gl-geocoder.css" type="text/css">
        <!-- Promise polyfill script required to use Mapbox GL Geocoder in IE 11 -->
        <script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.min.js"></script>
        
        <link href="{% static 'control/css/index.css' %}" rel="stylesheet">

        <meta name="robots" content="noindex" />
    </head>
    <body>
        <div id="react"></div>
        {% csrf_token %}
        <script src="{% static 'control/javascript/components.js' %}"></script>
        <script src="{% static 'control/javascript/index.js' %}"></script>
    </body>
</html>

templates/control/report.html
{% extends 'maps/nav.html' %}
{% load static %}

{% block head %}
    <title>Reportar otra cuenta u organización</title>
    <style>
        #titles {
            display: flex;
            justify-content: center;
            margin-top: 6vh;
        }

        h1 {
            margin: 0 2vw;
            font-size: 40px;
        }

        i {
            font-size: 40px;
            color: #ff3a3a;
        }

        form {
            width: 50%;
            margin-left: 25%;
            margin-top: 8vh;
        }

        form div {
            margin-bottom: 3vh;
        }

        label {
            display: block;
            font-size: 22px;
            font-weight: 500;
        }

        input, select, textarea {
            width: 100%;
            font-size: 15px;
            margin-top: 1vh;
            border: 1px solid rgb(192, 192, 192);
            padding: 2px 10px;
            border-radius: 5px;
        }

        input[type='submit'] {
            background-color: #ff3a3a;
            height: 4vh;
            font-size: 20px;
            color: #fff;
            border: none;
            cursor: pointer;
        }

        #message {
            margin-top: 2vh;
            margin-bottom: 2vh;
            color: #2c660a;
            font-size: 20px;
            text-align: center;
        }

        @media screen and (max-width: 1450px) {
            h1, i {
                font-size: 17px;
            }

            form {
                width: 80%;
                margin-left: 10%;
            }

            label {
                font-size: 15px;
            }

            input[type='submit'] {
                margin-bottom: 5vh;
                height: 35px;
            }
        }
        
    </style>
{% endblock %}

{% block content %}
    <div id="titles">
        <i class="fas fa-flag"></i>
        <h1>Reportar Cuenta u Organización</h1>
        <i class="fas fa-flag"></i>
    </div>
    <form method="POST"> {% csrf_token %}
        <div>
            <label for="id_organization_or_user">Organización o Usuario</label>
            {{form.organization_or_user}}
            {{form.organization_or_user.erros}}
        </div>
        <div>
            <label for="id_name_of_reported">Nombre del/los reportado(s)</label>
            {{form.name_of_reported}}
            {{form.name_of_reported.erros}}
        </div>
        <div>
            <label for="id_category_of_problem">Categoria del problema</label>
            {{form.category_of_problem}}
            {{form.category_of_problem.erros}}
        </div>
        <div>
            <label for="id_decription_of_the_problem">Descripción del problema</label>
            {{form.decription_of_the_problem}}
            {{form.decription_of_the_problem.erros}}
        </div>
        <input type="submit">
        <h6 id="message">{{message}}</h6>
    </form>
{% endblock %}