info/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('organizations', views.search, name='searchOrganization'),
    path('become', views.become, name='become'),
    path('about_us', views.about_us, name="aboutus"),
    path('terms_and_conditions', views.terms, name="terms"),
    path('organization/<int:pk>', views.organization, name='org'),
    path('categories/', views.choose_category, name='choose'),
    path('categories/<str:category>', views.category, name='category'),

    path('api/organizations', views.api_search, name='apiSearchOrg'),
    path('api/orgpoints', views.api_org, name='apiHelpOrg'),
    path('api/category', views.api_category, name='apiCategory')
]

login/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.account, name='account'),
    path('login', views.entry, name="login"),
    path('logout', views.out, name="logout"),
    path('register', views.register, name="register"),
    path('ranking', views.ranking, name="ranking"),
    path('another/<str:username>', views.another_account, name='another'),

    path('forgot', views.forgot_password, name='forgot'),
    path('forgot/email/<str:random_string>', views.email_link, name='emailink'),

    path('password/<int:re>', views.repassword, name='password'),
    path('password/reset/', views.reset_password, name='reset_password'),
    path('password/eliminate', views.eliminate, name='eliminate'),

    path('api/ranking', views.ranking_api, name="RankingAPI"),
    path('api/account', views.api_places, name='Apiplaces'),
    path('api/dark', views.dark_mode, name='dark')
] 

small_actions/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('maps.urls')),
    path('account/', include('login.urls')),
    path('info/', include('info.urls')),
    path('control/', include('control.urls')),
    path("ads.txt", TemplateView.as_view(template_name="emails/ads.txt", content_type="text/plain")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser): 
    points = models.PositiveIntegerField(default=0)
    photo = models.ImageField(upload_to="people", null=True, blank=True)
    latitude = models.DecimalField(max_digits=10, decimal_places=8, null=True, blank=True)
    longitude = models.DecimalField(max_digits=11, decimal_places=8, null=True, blank=True)
    visited = models.ManyToManyField('maps.Help', related_name="persons_visited", blank=True)
    can_change = models.BooleanField(null=True, blank=True) #Security
    dark_mode = models.BooleanField(default=False)
    #Forgot password
    date_forgot = models.DateTimeField(auto_now_add=True)
    random_string = models.CharField(max_length=20, blank=True, null=True, unique=True)

    def get_ranking(self):
        return list(User.objects.all().order_by('-points')).index(User.objects.get(username=self.username))

login/forms.py
from django import forms
from .models import User

class FormLogin(forms.Form):
    username = forms.CharField(max_length=32, widget=forms.TextInput(attrs={'placeholder':'Usuario'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Contraseña'}))

class FromCreateUser(forms.ModelForm):
    username = forms.CharField(max_length=32, widget=forms.TextInput(attrs={'placeholder':'Usuario'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Contraseña'}))
    repeat_password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Repita la Contraseña'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'placeholder': 'Email'})
        self.fields['latitude'].widget.attrs.update({'placeholder': 'Lat.'})
        self.fields['longitude'].widget.attrs.update({'placeholder': 'Long.'})

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'latitude', 'longitude', 'photo')

class ChangeUser(forms.ModelForm):
    username = forms.CharField(max_length=32, widget=forms.TextInput(attrs={'placeholder':'Usuario'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'placeholder': 'Email'})
        self.fields['latitude'].widget.attrs.update({'placeholder': 'Lat.'})
        self.fields['longitude'].widget.attrs.update({'placeholder': 'Long.'})

    class Meta:
        model = User
        fields = ('email', 'latitude', 'longitude', 'photo', 'dark_mode')

class FormPassword(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Contraseña'}))

class FormForgot(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder':'Email'}))

class ResetPassword(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Nueva Contraseña'}))
    repeat_password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Repita la Nueva Contraseña'}))

login/views.py
from django.shortcuts import render, redirect, reverse
from django.http import JsonResponse
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.core.mail import send_mail
from django.conf import settings
from django.template.loader import render_to_string
from django.core.cache import cache
from django.core.cache.utils import make_template_fragment_key

from .forms import FormLogin, FromCreateUser, ChangeUser, FormPassword, ResetPassword, FormForgot
from .models import User

import json
import random
import string
from datetime import timedelta

# Create your views here.

def entry(request):
    form = FormLogin()
    error = ""

    if request.method == "POST":
        form = FormLogin(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                #Cleand Nav Cache
                cache.delete(make_template_fragment_key('navbar'))

                if 'next' in request.POST and request.POST['next'] != '':
                    return redirect(request.POST['next'])
                return redirect(reverse('index'))
            else:
                error = "El usuario o contraseña son incorrectos"

    return render(request, 'login/login.html', {'form' : form, 'error' : error})

def out(request):
    logout(request)
    #Cleand Nav Cache
    cache.delete(make_template_fragment_key('navbar'))

    return redirect(reverse('index'))

@login_required(login_url='/account/login')
def account(request):
    user = User.objects.get(username=request.user)
    index = list(User.objects.order_by('-points')).index(user) + 1
    form = ChangeUser()

    if request.method == "POST":
        form = ChangeUser(request.POST, request.FILES)
        if form.is_valid():
            cache.delete(make_template_fragment_key('navbar')) #Cleand Nav Cache
            user.username =  form.cleaned_data['username']
            user.email =     form.cleaned_data['email']
            user.latitude =  form.cleaned_data['latitude']
            user.longitude = form.cleaned_data['longitude']
            if form.cleaned_data['photo'] != None:
                user.photo = form.cleaned_data['photo']
                
            try:
                user.save()
            except:
                pass

            return redirect(reverse('account'))

    #Achivments
    volunteer = len(user.visited.filter(mayor_category='V'))
    donate = len(user.visited.filter(mayor_category='D'))
    comments = len(user.comments.all())

    ctx = {'user' : user, 'index' : index, 'form' : form, 'volunteer' : volunteer, \
        'donate' : donate, 'comments' : comments}
    return render(request, 'login/account.html', ctx)

@login_required(login_url='/account/login')
def dark_mode(request):
    user = User.objects.get(username=request.user)
    user.dark_mode = not user.dark_mode
    user.save()
    return redirect(reverse('account'))

@login_required(login_url='/account/login')
def repassword(request, re): 
    form = FormPassword()
    error = ''

    if request.method == 'POST':
        form = FormPassword(request.POST)
        if form.is_valid():
            user = authenticate(username=request.user.username, password=form.cleaned_data['password'])
            if user is not None:
                user = User.objects.get(username=request.user.username)
                user.can_change = True
                user.save()
                return redirect(reverse('eliminate' if re == 2 else 'reset_password'))
            else:
                error = "No coincide con tu contraseña"

    return render(request, 'login/repassword.html', {'form' : form, 'error' : error})

@login_required(login_url='/account/login')
def reset_password(request):
    if request.user.can_change:
        form = ResetPassword()
        error = ''

        if request.method == 'POST':
            form = ResetPassword(request.POST)
            if form.is_valid():
                if form.cleaned_data['password'] == form.cleaned_data['repeat_password']:
                    user = User.objects.get(username=request.user)
                    user.set_password(form.cleaned_data['password'])
                    user.can_change = False
                    user.save()

                    return redirect(reverse('account'))
                else:
                    error = "Las contraseñas no coinciden"

        return render(request, 'login/reset_password.html', {'form' : form, 'error' : error})
    else:
        return redirect(reverse('password', kwargs={'re' : 1})) 

@login_required(login_url='/account/login')
def eliminate(request):
    if request.user.can_change:
        if request.method == 'POST':
            user = User.objects.get(username=request.user)
            if request.POST['answer'] == 'no':
                user.can_change = False
                user.save()
                return redirect(reverse('account'))
            elif request.POST['answer'] == 'yes':
                user.delete()
                return redirect(reverse('index'))

        return render(request, 'login/eliminate.html')
    else:
        return redirect(reverse('password', kwargs={'re' : 2})) 

def register(request):
    form = FromCreateUser()
    error = ""

    if request.method == "POST":
        form = FromCreateUser(request.POST, request.FILES)
        if form.is_valid():
            if form.cleaned_data['password'] == form.cleaned_data['repeat_password']:
                new_user = User.objects.create_user(
                    username=   form.cleaned_data['username'],
                    password=   form.cleaned_data['password'],
                    email=      form.cleaned_data['email'],
                    latitude=   form.cleaned_data['latitude'],
                    longitude = form.cleaned_data['longitude'],
                    photo =     form.cleaned_data['photo']
                )

                group = Group.objects.get(name='Client')
                new_user.groups.add(group)
                new_user.save()
                
                if 'next' in request.POST:
                    next_f = request.POST['next']
                    return redirect(reverse('login') + f'?next={next_f}')

                return redirect(reverse('login'))
            else:
                error = "Las contraseñas no coinciden"

    return render(request, 'login/register.html', {'form' : form, 'error':error})


@login_required(login_url='/account/login')
def ranking(request):
    user = User.objects.get(username=request.user)
    all_ranking = User.objects.all().order_by('-points')
    ranking = list(all_ranking).index(user)

    ctx = {'frist' : all_ranking[:3], 'ranking' : ranking}
    return render(request, 'login/ranking.html', ctx)


def ranking_api(request):
    if request.method != "POST":
        return JsonResponse({'error' : 'The request must be POST'}, status=400)
 
    data = json.loads(request.body)

    if 'start' in data and 'end' in data:
        start = int(data['start'])
        end = int(data['end'])
        if start == 0:
            return JsonResponse({'error' : 'Start cant be cero'})
        
        users = User.objects.all()
        if end > len(users) + 20:
            return JsonResponse({'last' : 'No more elements'})

        results = users.order_by('-points')[start - 1 : end]
        response = {'people' : []}
        for i in range(len(results)):
            response['people'].append({
                'ranking' : start + i,
                'username' : results[i].username,
                'points' : results[i].points
            })
        return JsonResponse(response, status=200)

    else:
        return JsonResponse({'error' : 'please provide start and end'}, status=400)


def forgot_password(request):
    form = FormForgot()
    succes = False
    if request.method == 'POST':
        form = FormForgot(request.POST)
        if form.is_valid():
            results = User.objects.filter(email=form.cleaned_data['email'])
            if len(results) > 0:
                #Configure for url
                user = results[0]

                user.date_forgot = timezone.now() + timedelta(minutes=15)
                letters = string.ascii_letters
                user.random_string = ''.join(random.choice(letters) for i in range(20))
                user.save()
                
                #Send Email
                link = 'https://www.small-actions.com' + reverse('emailink', kwargs={'random_string' : user.random_string})
                html_message = render_to_string('login/email.html', {'link': link})

                send_mail('¿Olvidaste tu contraseña?',
                f"Por favor ingresa a este link: {link}",
                settings.EMAIL_HOST_USER,
                [user.email],
                html_message=html_message)

        succes = True #For not telling if a email exist, always succes no matter the email

    return render(request, 'login/forgot.html', {'form' : form, 'succes' : succes})

def email_link(request, random_string):
    users = User.objects.filter(random_string=random_string) #Check if user
    if len(users) > 0:
        user = users[0]
        if timezone.now() <= user.date_forgot: #Chek if link is not expired
            form = ResetPassword()
            error = ''

            if request.method == 'POST':
                form = ResetPassword(request.POST)
                if form.is_valid():
                    if form.cleaned_data['password'] == form.cleaned_data['repeat_password']:
                        user.set_password(form.cleaned_data['password'])
                        letters = string.ascii_letters

templates/login/account.html
{% extends 'maps/nav.html' %}
{% load static %}
  
    {% block head %}
        <title>Cuenta: {{user.username}}</title>
        <script src="{% static 'control/javascript/mapbox-gl.js' %}"></script>
        <link href="{% static 'control/css/mapbox-gl.css' %}" rel='stylesheet' />

        <link href="{% static 'login/css/account.css' %}" rel="stylesheet">
    {% endblock %}
     
    {% block content %}
        <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
            <div id='info'>
                <div id="title_container">
                    <h1>{{user.username}}</h1>
                    {{form.username}}
                    {{form.username.errors}}
                    <span>{{error}}</span>
                    <a href="{% url 'ranking' %}"><h2>#{{index}}</h2></a>
                    <div id="dark_mode">
                        <i class="far fa-moon"></i>
                        <i class="fas fa-circle" id="dark_circle"></i>
                        <i class="far fa-sun" id="sun"></i>
                    </div>
                </div>
                <div id="info_info">
                    <div id="email_container">
                        <h3>Email:</h3>
                        <h4 id="h4">{{user.email}}</h4>
                        {{form.email}}
                        {{form.email.errors}}
                    </div>
                    <div>
                        <h5 id="coordinates_title">Coordenadas:</h5>
                        <h5 id="cordiantes">
                            <span id="latitude">{{user.latitude}}</span>
                            {{form.latitude}} 
                            <span>-</span> 
                            <span id="longitude">{{user.longitude}}</span>
                            {{form.longitude}}
                        </h5>
                        {{form.latitude.errors}}
                        {{form.longitude.errors}}
                        <p id="security"><i class="fas fa-lock"></i>Solo tu puedes ver esto</p>
                    </div>
                </div>
                <img src="{% static 'login/images/account.png' %}" alt='person' id="person">
                <div>
                    <h6 id="where">Donde ayudaste:</h6>
                    <div id="map"></div>
                </div>

            </div>
            <div id="links">
                <div id="img_container">
                    {% if request.user.photo %}
                        <img src="{{request.user.photo.url}}" alt="account" id="account_photo">
                    {% else %}
                        <img src="{% static 'maps/images/logo_small_icon_only_inverted.png' %}" alt="account" id="account_prede">
                    {% endif %}
                    {{form.photo}}
                    {{form.photo.errors}}
                </div>

                <div id="links_links">
                    <a id="change">Cambiar Info.</a>
                    <a href="{% url 'password' 1 %}">Cambiar Contraseña</a>
                    <a href="https://api.whatsapp.com/send?phone=573023986488">Atención al cliente</a>
                    <a href="{% url 'ranking' %}">Ver Ranking</a>
                    <a class="danger" href="{% url 'password' 2 %}">Eliminar Cuenta</a>
                    <a id="report" class="danger" href="{% url 'report' %}">Reportar otra cuenta u organización</a>
                </div>
            </div>
        </form>
        <div id="achiv">
            <div class="category">
                <h6>Consigue 1.000 Puntos</h6>
                <div class="bar">
                    <div class="progress" data-type="p" data-quantity="1000"></div>
                    <h6 class="number_progress"></h6>
                </div>
            </div>
            <div class="category">
                <h6>Visitar 10 Lugares</h6>
                <div class="bar">
                    <div class="progress" data-type="l" data-quantity="10"></div>
                    <h6 class="number_progress"></h6>
                </div>
            </div>
            <div class="category">
                <h6>Visitar 5 Voluntariados</h6>
                <div class="bar">
                    <div class="progress" data-type="v" data-quantity="5"></div>
                    <h6 class="number_progress"></h6>
                </div>
            </div>
            <div class="category">
                <h6 >Visitar 5 Donaciones</h6>
                <div class="bar">
                    <div class="progress" data-type="d" data-quantity="5"></div>
                    <h6 class="number_progress"></h6>
                </div>
            </div>
            <div class="category">
                <h6>Realizar 50 Comentarios</h6>
                <div class="bar">
                    <div class="progress" data-type="c" data-quantity="50"></div>
                    <h6 class="number_progress"></h6>
                </div>
            </div>
            <div class="category">
                <h6>Pon una foto de perfil</h6>
                <div class="bar">
                    <div class="progress" data-type="pr"></div>
                    <h6 class="number_progress"></h6>
                </div>
            </div>
            <div class="category">
                <h6>Consigue 5.000 Puntos</h6>
                <div class="bar">
                    <div class="progress" data-type="p" data-quantity="5000"></div>
                    <h6 class="number_progress"></h6>
                </div>
            </div>
            <div class="category">
                <h6>Visitar 50 Lugares</h6>
                <div class="bar">
                    <div class="progress" data-type="l" data-quantity="50"></div>
                    <h6 class="number_progress"></h6>
                </div>
            </div>
            <div class="category">
                <h6>Visitar 25 Voluntariados</h6>
                <div class="bar">
                    <div class="progress" data-type="v" data-quantity="25"></div>
                    <h6 class="number_progress"></h6>
                </div>
            </div>
            <div class="category">
                <h6>Visitar 25 Donaciones</h6>
                <div class="bar">
                    <div class="progress" data-type="d" data-quantity="25"></div>
                    <h6 class="number_progress"></h6>
                </div>
            </div>
        </div>
        <div id="info-bars" style="display: none;">
            <span id="p">{{user.points}}</span>
            <span id="l">{{user.visited.all | length }}</span>
            <span id="v">{{volunteer}}</span>
            <span id="d">{{donate}}</span>
            <span id="c">{{comments}}</span>
            <span id="pr">{{user.photo}}</span>
        </div>
        <script src="{% static 'login/javascript/account.js' %}"></script>
    {% endblock %}
  

templates/login/another.html
{% extends 'maps/nav.html' %}
{% load static %}

{% block head %}
    <title>Cuenta de {{user.username}}</title>
    <link href="{% static 'login/css/another.css' %}" rel="stylesheet">
{% endblock %}
     
{% block content %}
    <div id="title_div">
        {% if user.photo %}
        <img src="{{user.photo.url}}" alt="account" id="title_photo" width="70" height="70">
        {% else %}
        <img src="{% static 'maps/images/logo_small_icon_only_inverted.png' %}" alt="account" width="70" height="70">
        {% endif %}

        <h1>{{user.username}}</h1>
    </div>
    <div id="infos">
        <div id="frist_info">
            <i class="fas fa-trophy"></i>
            <h2>#{{place}} en el mundo</h2>
        </div>
        <div>
            <i class="fas fa-user-plus"></i>
            <h3>{{user.points}} puntos</h3>
        </div>
        <div id="last_info">
            <i class="fas fa-user-plus"></i>
            <h4>{{user.visited.all | length }} lugares visitados</h4>
        </div>
    </div>
{% endblock %}

templates/login/eliminate.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Eliminar: {{request.user}}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            * {
                font-family: 'Sora', sans-serif;
            }

            h1, input, p {
                width: 50vw;
                margin-left: 25vw;
            }

            h1 {
                text-align: center;
                font-size: 60px;
                margin-top: 20vh;
                color: #ff3a3a;
            }

            input {
                font-size: 25px;
                margin-top: 5vh;
                border-radius: 15px;
                padding: 10px;                
                border: none;
                cursor: pointer;
            }

            p {
                margin-top: 5vh;
                text-align: justify;
            }

            #sure {
                background-color: #ff3a3a;
                color: #fff;
            }

            input[type='submit'] {
                background-color: #000;
                color: #fff;
            }

        </style>
    </head>
    <body>
        <h1>¿Estás seguro que quiere eliminar la cuenta {{request.user}}?</h1>
        <form method="POST"> {% csrf_token %}
            <input type="hidden" value="yes" name="answer">
            <input type="submit" value="Sí, estoy seguro" id="sure">
        </form>
        <form method="POST"> {% csrf_token %}
            <input type="hidden" value="no" name="answer">
            <input type="submit" value="No, no lo estoy">
        </form>
        <p>Si dices que si, tu cuenta no existirá más, tus puntos, ranking, e información personal como email, usuario, coordenadas, y lugar donde ayudaste serán eliminados y no podrás recuperar tu cuenta jamás.</p>
    </body>
</html>

templates/login/email.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Correo de recuperar contraseña</title>
        <style>
            * {
                font-family: 'Sora', sans-serif;
            }

            h2 {
                color: #ff3a3a;
                font-size: 30px;
                height: 50px;
                border-bottom: 2px solid #ff3a3a;
            }

            h1 {
                font-size: 40px;
                text-align: center;
                margin-top: 5vh;
            }

            a button {
                width: 50vw;
                margin-left: 21vw;
                font-size: 25px;
                background-color: #ff3a3a;
                color: #fff;
                padding: 0.5vh 2vw;
                margin-top: 4vh;
                border: none;
                border-radius: 25px;
            }

            #frist {
                margin-top: 15vh;
            }

            p {
                font-size: 10px;
                width: 90vw;
                margin-left: 5vw;
                margin-bottom: 1vh;
            }

        </style>
    </head>
    <body>
        <div>
            <h2>Small Actions</h2>
        </div>
        <div>
            <h1>¿Olvidaste tu contraseña?</h1>
            <a href="{{link}}"><button>Recuperar Cuenta</button></a>
            <p id="frist">O visita este link: <a href="{{link}}">{{link}}</a></p>
            <p>Este link expira en 15 minutos, si creas uno nuevo este no funcionara mas.</p>
        </div>
    </body>  
</html>

templates/login/forgot.html
{% extends 'maps/nav.html' %}

{% block head %}
    <title>Recuperar Cuenta</title>
    <style>
        h1 {
            text-align: center;
            font-size: 40px;
            margin-top: 7vh;
        }
        input {
            width: 46vw;
            margin-left: 25vw;
            font-size: 25px;
            padding: 0.5vh 2vw;
            margin-top: 5vh;
            border-radius: 10px;
            border: 1px solid rgb(199, 199, 199);
        }

        input[type='submit'] {
            width: 50.2vw;
            background-color: #ff3a3a;
            border: none;
            color: #fff;
            cursor: pointer;
        }

        p {
            font-size: 25px;
            color: rgb(6, 214, 6);
            text-align: center;
            margin-top: 5vh;
        }

        #return {
            font-size: 20px;
            margin-top: 3vh;
            width: 100%;
            display: block;
            text-align: center;
            color: #000;
        }

        @media screen and (max-width: 1450px) {
            input {
                width: 92vw;
                margin-left: 2vw;
            }
            input[type='submit'] {
                width: 96vw;
            }
        }


    </style>
{% endblock %}
     
{% block content %}
    <div>
        <h1>Ingresa tu email:</h1>
        <form method="POST"> {% csrf_token %}
            {{form.email}}
            {{form.email.errors}}
            <input type="submit" value="Send Email">
        </form>
        {% if succes %}
            <p>El correo fue enviado <i class="fas fa-check"></i></p>
            <a href="{% url 'login' %}" id="return">Volver a ingresar</a>
        {% endif %}
    </div>
{% endblock %}

templates/login/register.html
{% extends 'maps/nav.html' %}
{% load static %}
  
{% block head %}
    <title>Registrarse | Small Actions</title>
    <link href="{% static 'login/css/register.css' %}" rel="stylesheet">
{% endblock %}
    
{% block content %}
    <div id="all_for">
        <h1>Crear Cuenta</h1>
        <span>{{error}}</span>
        <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
            <input type="hidden" value="{{request.GET.next}}" name="next">
            <div id="grid">
                <div class="input_container">
                    <i class="fas fa-user-circle"></i>
                    {{form.username}}
                    <span>{{form.username.errors}}</span>
                </div>
                <div class="input_container">
                    <i class="fas fa-envelope"></i>
                    {{form.email}}
                    <span>{{form.email.errors}}</span>
                </div>
                <div class="input_container">
                    <i class="fas fa-lock"></i>
                    {{form.password}}
                    <span>{{form.password.errors}}</span>
                </div>
                <div class="input_container">
                    <i class="fas fa-redo"></i>
                    {{form.repeat_password}}
                    <span>{{form.repeat_password.errors}}</span>
                </div>
            </div>
            
            <div id="optional_super">
                <div class="optional_container">
                    <h3>Coordenadas</h3>
                    <div id="lat_long">
                        {{form.latitude}}
                        <span>{{form.latitude.errors}}</span>
                        {{form.longitude}}
                        <span>{{form.longitude.errors}}</span>
                    </div>
                    <p>Esto es opcional, nosotros no queremos rastrearte, entonces, para tener una experiencia personalizada, por favor ingresa tu coordenadas. Nosotros garantizamos que nadie las verá.</p>
                </div>
                <div class="optional_container" id="rigth_opt">
                    <h3>Foto de perfil:</h3>
                    {{form.photo}}
                    <span>{{form.photo.errors}}</span>
                    <p>Esto es opcional, la foto puede que sea mostrada al público.</p>
                </div>
            </div>

            <input type="submit" value="Registrarse">
        </form>
        <script>
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(showPosition);
            } else {
                console.log('Not suported geolocation');
            }

            function showPosition(position) {
                const latitude = document.querySelector('#id_latitude');
                const longitude = document.querySelector('#id_longitude');
                latitude.value = position.coords.latitude.toFixed(8);
                longitude.value = position.coords.longitude.toFixed(8);
            }
        </script>
    </div>
    <p id="legal">Al registrarte aceptas los <a href="{% url 'terms' %}">Términos y Condiciones</a> y la <a href="{% url 'terms' %}#priv">Política de privacidad</a></p>
{% endblock %}